# ---
# apiVersion: "v1"
# kind: "Namespace"
# metadata:
#   name: "project"
# ---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "task-1-service"
  # namespace: "project"
  labels:
    app: "test-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "test-app"
  type: "LoadBalancer"