apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mongo-url: bW9uZ29kYjovL2FwcDphcHBAbW9uZ28tbW9uZ29kYi0wLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nby1tb25nb2RiLTEubW9uZ28tbW9uZ29kYi1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvLW1vbmdvZGItMi5tb25nby1tb25nb2RiLWhlYWRsZXNzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcK
