apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mongo-url: bW9uZ29kYjovL3Jvb3Q6cm9vdEBhcHAtbW9uZ29kYi1oZWFkbGVzcwo=
  db-password: {{ .Values.mongodb.rootPassword64 }}
  db-username: {{ .Values.mongodb.rootUser }}